# Generated by Django 4.2.7 on 2025-08-02 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of the attachment', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment')),
                ('file', models.FileField(help_text='Upload file (PDF, image, document, etc.)', upload_to='lease_attachments/')),
                ('file_type', models.CharField(choices=[('lease_agreement', 'Lease Agreement'), ('addendum', 'Addendum'), ('inspection_report', 'Inspection Report'), ('maintenance_request', 'Maintenance Request'), ('payment_proof', 'Payment Proof'), ('correspondence', 'Correspondence'), ('photo', 'Photo'), ('other', 'Other')], default='other', help_text='Type of attachment', max_length=20)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this attachment is visible to tenants')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tenants.lease')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Attachment',
                'verbose_name_plural': 'Lease Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
