# Generated by Django 4.2.7 on 2025-08-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_stripeinvoice_lease'),
        ('finance', '0004_alter_invoice_lease'),
        ('tenants', '0003_leaseattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseattachment',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='leaseattachment',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='LeaseAttachment',
        ),
    ]
