# Generated by Django 4.2.7 on 2025-08-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_performance_indexes'),
        ('tenants', '0004_remove_leaseattachment_lease_and_more'),
    ]

    operations = [
    ]
