# Generated by Django 4.2.7 on 2025-08-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_merge_20250804_0037'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenant_employment_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenant_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenant_code_idx',
        ),
    ]
