# Generated by Django 4.2.7 on 2025-06-05 15:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Property name or identifier', max_length=200)),
                ('address', models.TextField(help_text='Full property address')),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('mixed_use', 'Mixed Use')], default='residential', help_text='Type of property', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Original purchase price in ZAR', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_market_value', models.DecimalField(decimal_places=2, help_text='Current estimated market value in ZAR', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_units', models.PositiveIntegerField(default=1, help_text='Total number of units in this property')),
                ('description', models.TextField(blank=True, help_text='Additional property details', null=True)),
                ('title_deed', models.FileField(blank=True, help_text='Title deed document', null=True, upload_to='documents/title_deeds/')),
                ('compliance_certificate', models.FileField(blank=True, help_text='Compliance certificate', null=True, upload_to='documents/compliance/')),
                ('property_image', models.ImageField(blank=True, help_text='Property main image', null=True, upload_to='images/properties/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this property actively managed?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties_property',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text="Unit number or identifier (e.g., '101', 'A1', 'Shop 5')", max_length=20)),
                ('unit_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4+ Bedroom'), ('office', 'Office'), ('retail', 'Retail Space'), ('warehouse', 'Warehouse'), ('parking', 'Parking Space'), ('other', 'Other')], default='1_bedroom', help_text='Type of unit', max_length=20)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('renovation', 'Under Renovation')], default='vacant', help_text='Current status of the unit', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rental amount in ZAR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Unit size in square meters', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='Additional unit details', null=True)),
                ('unit_image', models.ImageField(blank=True, help_text='Unit image', null=True, upload_to='images/units/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this unit actively available for rent?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.ForeignKey(help_text='Property this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'properties_unit',
                'ordering': ['property_ref__name', 'unit_number'],
                'unique_together': {('property_ref', 'unit_number')},
            },
        ),
    ]
