# Generated by Django 4.2.7 on 2025-08-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parent_property',
            field=models.ForeignKey(blank=True, help_text='Parent property (for sub-properties like individual apartments in a block)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_properties', to='properties.property'),
        ),
    ]
