# Generated by Django 4.2.7 on 2025-08-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_performance_indexes'),
        ('properties', '0002_property_parent_property'),
    ]

    operations = [
    ]
