# Generated by Django 4.2.7 on 2025-08-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_merge_20250804_0037'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='property_status_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_type_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_rent_idx',
        ),
    ]
