# Generated by Django 4.2.7 on 2025-07-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_invoicelineitem_invoicepayment_invoicetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('regular', 'Regular Monthly Invoice'), ('interim', 'Interim Adjustment Invoice'), ('late_fee', 'Late Fee Invoice'), ('credit', 'Credit Note')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Invoice is locked and cannot be edited'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was locked', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parent_invoice',
            field=models.ForeignKey(blank=True, help_text='Parent invoice for interim/adjustment invoices', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_invoices', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was sent', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('locked', 'Locked'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('locked', 'Locked'), ('paid', 'Marked as Paid'), ('cancelled', 'Cancelled'), ('unlocked', 'Unlocked (Admin Override)'), ('line_item_added', 'Line Item Added'), ('line_item_updated', 'Line Item Updated'), ('line_item_deleted', 'Line Item Deleted'), ('payment_recorded', 'Payment Recorded')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the change')),
                ('field_changed', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('invoice_snapshot', models.JSONField(blank=True, help_text='Full invoice state at time of change', null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Audit Log',
                'verbose_name_plural': 'Invoice Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['invoice', '-timestamp'], name='finance_inv_invoice_7bf294_idx'), models.Index(fields=['action', '-timestamp'], name='finance_inv_action_ccc38c_idx'), models.Index(fields=['user', '-timestamp'], name='finance_inv_user_id_ed0589_idx')],
            },
        ),
    ]
