# Generated by Django 4.2.7 on 2025-08-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        ('finance', '0003_invoice_locking_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='leases.lease'),
        ),
    ]
