# Generated by Django 4.2.7 on 2025-08-05 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0008_remove_lease_lease_status_idx_and_more'),
        ('tenants', '0006_remove_tenant_tenant_status_idx_and_more'),
        ('finance', '0004_alter_invoice_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
                ('setting_type', models.CharField(choices=[('vat_rate', 'VAT Rate'), ('invoice_terms', 'Invoice Terms'), ('late_fee_compound', 'Late Fee Compounding')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid towards this invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance due', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateField(blank=True, help_text='End date of billing period', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(blank=True, help_text='Start date of billing period', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='scheduled_send_date',
            field=models.DateField(blank=True, help_text='Date when invoice should be automatically sent', null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount allocated to this specific invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='is_overpayment',
            field=models.BooleanField(default=False, help_text='True if this payment exceeds the invoice total'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued to Send'), ('sent', 'Sent'), ('locked', 'Locked'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('check', 'Check'), ('credit_balance', 'Credit Balance Application'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='TenantCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Credit Balance',
                'verbose_name_plural': 'Tenant Credit Balances',
            },
        ),
        migrations.CreateModel(
            name='RentEscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escalation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('escalation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateField()),
                ('reason', models.CharField(default='Annual Escalation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_escalations', to='leases.lease')),
            ],
            options={
                'verbose_name': 'Rent Escalation Log',
                'verbose_name_plural': 'Rent Escalation Logs',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('utility', 'Utility Charges'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('storage', 'Storage'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charges', to='leases.lease')),
            ],
            options={
                'verbose_name': 'Recurring Charge',
                'verbose_name_plural': 'Recurring Charges',
                'ordering': ['category', 'description'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='First day of the billing month')),
                ('draft_data', models.JSONField(help_text='Stored invoice data including line items and modifications')),
                ('user_modified', models.BooleanField(default=False, help_text='True if user has made changes to this draft')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_drafts', to='leases.lease')),
            ],
            options={
                'verbose_name': 'Invoice Draft',
                'verbose_name_plural': 'Invoice Drafts',
                'ordering': ['billing_month'],
                'unique_together': {('lease', 'billing_month')},
            },
        ),
    ]
