# Generated by Django 4.2.7 on 2025-08-26 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_remove_tenant_tenant_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_banktransaction_manualpayment_paymentallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderpaymentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shortfall_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alert_message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='underpayment_alerts', to='finance.banktransaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underpayment_alerts', to='finance.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='underpayment_alerts', to='finance.manualpayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underpayment_alerts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Underpayment Alert',
                'verbose_name_plural': 'Underpayment Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('waiver', 'Waiver'), ('discount', 'Discount'), ('credit', 'Credit'), ('penalty', 'Penalty'), ('correction', 'Correction'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('pre_adjustment_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('post_adjustment_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField()),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.adjustment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_audit_logs', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Adjustment Audit Log',
                'verbose_name_plural': 'Adjustment Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
