# Generated by Django 4.2.7 on 2025-07-24 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_id', models.CharField(help_text="Strike's quote ID", max_length=255, unique=True)),
                ('bolt11', models.TextField(help_text='Lightning payment request')),
                ('btc_amount', models.DecimalField(decimal_places=8, help_text='Amount in BTC', max_digits=16)),
                ('exchange_rate', models.DecimalField(decimal_places=8, help_text='ZAR to BTC exchange rate', max_digits=20)),
                ('expires_at', models.DateTimeField(help_text='Quote expiration time')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lightning Quote',
                'verbose_name_plural': 'Lightning Quotes',
                'db_table': 'payments_lightning_quote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_zar', models.DecimalField(decimal_places=2, help_text='Amount in ZAR', max_digits=10)),
                ('currency', models.CharField(choices=[('ZAR', 'South African Rand'), ('BTC', 'Bitcoin')], default='ZAR', max_length=3)),
                ('description', models.TextField(help_text="Invoice description (e.g., 'Rent for July 2024')")),
                ('invoice_month', models.CharField(help_text="YYYY-MM format (e.g., '2024-07')", max_length=7)),
                ('invoice_year', models.IntegerField()),
                ('strike_invoice_id', models.CharField(help_text="Strike's invoice ID", max_length=255, unique=True)),
                ('strike_payment_request', models.TextField(blank=True, help_text='Lightning payment request (bolt11)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quote_generated', 'Quote Generated'), ('paid', 'Paid'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('payment_url', models.URLField(blank=True, help_text='Frontend payment URL', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lightning_invoices', to='tenants.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightning_invoices', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Strike Invoice',
                'verbose_name_plural': 'Strike Invoices',
                'db_table': 'payments_strike_invoice',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'invoice_month')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('invoice.created', 'Invoice Created'), ('invoice.updated', 'Invoice Updated'), ('invoice.paid', 'Invoice Paid'), ('invoice.canceled', 'Invoice Canceled')], max_length=50)),
                ('event_id', models.CharField(help_text="Strike's event ID", max_length=255, unique=True)),
                ('raw_data', models.JSONField(help_text='Raw webhook payload from Strike')),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('strike_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.stripeinvoice')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'payments_webhook_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_hash', models.CharField(help_text='Lightning transaction hash', max_length=255, unique=True)),
                ('amount_zar', models.DecimalField(decimal_places=2, help_text='Amount paid in ZAR', max_digits=10)),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Amount paid in BTC', max_digits=16)),
                ('strike_payment_id', models.CharField(help_text="Strike's payment ID", max_length=255, unique=True)),
                ('webhook_received_at', models.DateTimeField(help_text='When webhook was received')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('lightning_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.lightningquote')),
                ('strike_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.stripeinvoice')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payments_payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lightningquote',
            name='strike_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='payments.stripeinvoice'),
        ),
    ]
