# Generated by Django 4.2.7 on 2025-08-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeinvoice',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lightning_invoices', to='leases.lease'),
        ),
    ]
