# Generated by Django 4.2.7 on 2025-08-02 10:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Whether lease automatically renews'),
        ),
        migrations.AddField(
            model_name='lease',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Grace period in days before late fees apply'),
        ),
        migrations.AddField(
            model_name='lease',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date when invoices should be generated', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord',
            field=models.ForeignKey(blank=True, help_text='Landlord for this lease', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee as percentage of rent', max_digits=5),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of lease in months', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(choices=[('Fixed', 'Fixed Term'), ('Month-to-Month', 'Month-to-Month'), ('Periodic', 'Periodic')], default='Fixed', help_text='Type of lease agreement', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='management_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Management fee as percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='lease',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the lease'),
        ),
        migrations.AddField(
            model_name='lease',
            name='notice_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Notice period required to terminate lease'),
        ),
        migrations.AddField(
            model_name='lease',
            name='pro_rata_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pro-rata amount for partial months', max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='procurement_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Procurement fee as percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_due_day',
            field=models.PositiveIntegerField(default=1, help_text='Day of month when rent is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='lease',
            name='rental_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], default='Monthly', help_text='How often rent is due', max_length=20),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending', 'Pending'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lease',
            name='terms',
            field=models.TextField(blank=True, help_text='Lease terms and conditions'),
        ),
    ]
