# Generated by Django 4.2.7 on 2025-08-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
        ('leases', '0002_lease_auto_renew_lease_grace_period_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='landlord',
            field=models.ForeignKey(blank=True, help_text='Landlord for this lease', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='landlords.landlord'),
        ),
    ]
