# Generated by Django 4.2.7 on 2025-08-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_alter_lease_landlord'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(
                fields=['property'],
                condition=models.Q(status__in=['active', 'pending']),
                name='unique_active_lease_per_property'
            ),
        ),
    ]
