# Generated by Django 4.2.7 on 2025-08-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_add_property_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lease',
            name='unique_active_lease_per_property',
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee as fixed amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_type',
            field=models.CharField(choices=[('percentage', 'Percentage of Rent'), ('amount', 'Fixed Amount')], default='percentage', help_text='Type of late fee calculation', max_length=20),
        ),
    ]
