# Generated by Django 4.2.7 on 2025-08-02 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0005_add_late_fee_type_and_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the note', max_length=255)),
                ('content', models.TextField(help_text='Content of the note')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('important', 'Important'), ('maintenance', 'Maintenance'), ('payment', 'Payment'), ('inspection', 'Inspection'), ('renewal', 'Renewal'), ('termination', 'Termination'), ('other', 'Other')], default='general', help_text='Type of note', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_notes_created', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_notes', to='leases.lease')),
            ],
            options={
                'verbose_name': 'Lease Note',
                'verbose_name_plural': 'Lease Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
