# Generated by Django 4.2.7 on 2025-08-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lease',
            name='lease_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='lease',
            name='lease_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='lease',
            name='lease_property_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='lease',
            name='lease_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='lease',
            name='lease_created_at_idx',
        ),
        migrations.AddField(
            model_name='lease',
            name='escalation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed escalation amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='escalation_date',
            field=models.DateField(blank=True, help_text='Date when rent escalation should occur annually', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='escalation_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual escalation percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='lease',
            name='escalation_type',
            field=models.CharField(choices=[('percentage', 'Percentage Increase'), ('amount', 'Fixed Amount Increase'), ('none', 'No Escalation')], default='none', help_text='Type of rent escalation', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='next_escalation_date',
            field=models.DateField(blank=True, help_text='Next scheduled escalation date', null=True),
        ),
    ]
