# Generated by Django 4.2.7 on 2025-08-01 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name for individual or contact person name for company/trust', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company'), ('Trust', 'Trust')], default='Individual', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Company or trust name', max_length=255)),
                ('vat_number', models.CharField(blank=True, help_text='VAT registration number', max_length=20)),
                ('id_number', models.CharField(blank=True, help_text='South African ID number', max_length=20)),
                ('tax_number', models.CharField(blank=True, help_text='Tax registration number', max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, choices=[('western_cape', 'Western Cape'), ('gauteng', 'Gauteng'), ('kwazulu_natal', 'KwaZulu-Natal'), ('eastern_cape', 'Eastern Cape'), ('free_state', 'Free State'), ('limpopo', 'Limpopo'), ('mpumalanga', 'Mpumalanga'), ('north_west', 'North West'), ('northern_cape', 'Northern Cape')], max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='South Africa', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('branch_code', models.CharField(blank=True, max_length=10)),
                ('account_type', models.CharField(blank=True, choices=[('current', 'Current'), ('savings', 'Savings'), ('transmission', 'Transmission')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the landlord')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
                'db_table': 'landlords_landlord',
                'ordering': ['-created_at'],
            },
        ),
    ]
