# Generated by Django 4.2.7 on 2025-07-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='webauthn_challenge',
            field=models.CharField(blank=True, help_text='Temporary challenge for WebAuthn registration/login', max_length=500, null=True),
        ),
    ]
