# Generated by Django 4.2.7 on 2025-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_webauthn_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dashboard_preferences',
            field=models.JSONField(blank=True, default=dict, help_text="User's dashboard customization preferences", null=True),
        ),
    ]
