# Generated by Django 4.2.7 on 2025-08-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_dashboard_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, help_text='Company or organization the user belongs to', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('basic_user', 'Basic User'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('maintenance_operator', 'Maintenance Operator'), ('property_administrator', 'Property Administrator'), ('finance_administrator', 'Finance Administrator'), ('manager', 'Manager'), ('superuser', 'SuperUser')], default='basic_user', help_text="User's role in the system", max_length=50),
        ),
    ]
