# Generated by Django 4.2.7 on 2025-08-01 22:28

from django.db import migrations


def update_existing_users_to_basic_role(apps, schema_editor):
    """Update existing users to have basic_user role and sync legacy fields."""
    CustomUser = apps.get_model('users', 'CustomUser')
    
    # Update all users to basic_user role if they don't have a role set
    users_without_role = CustomUser.objects.filter(role__isnull=True)
    users_without_role.update(role='basic_user')
    
    # Sync legacy boolean fields with new role field
    for user in CustomUser.objects.all():
        if user.is_landlord and user.role == 'basic_user':
            user.role = 'landlord'
            user.save()
        elif user.is_tenant and user.role == 'basic_user':
            user.role = 'tenant'
            user.save()


def reverse_update_existing_users_to_basic_role(apps, schema_editor):
    """Reverse the migration - set all users back to basic_user role."""
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.all().update(role='basic_user')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_company_customuser_role'),
    ]

    operations = [
        migrations.RunPython(
            update_existing_users_to_basic_role,
            reverse_update_existing_users_to_basic_role
        ),
    ]
