# Generated by Django 4.2.7 on 2025-08-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_management', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debtauditlog',
            name='debtauditlog_debtor_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtauditlog',
            name='debtauditlog_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtauditlog',
            name='debtauditlog_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtdocument',
            name='debtdocument_debtor_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtdocument',
            name='debtdocument_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtdocument',
            name='debtdocument_uploaded_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='debtor_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='debtor_assigned_to_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='debtor_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='debtor_last_contact_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='debtor_total_debt_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtpayment',
            name='debtpayment_debtor_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtpayment',
            name='debtpayment_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='debtpayment',
            name='debtpayment_method_idx',
        ),
    ]
